### ISSUE TITLE
how can we run it?

### ISSUE THREAD

**Issue by ryankaka92** [drbobbeaty/Quip#1]
can we run this on command line and pass letters as paramters?

**Comment by drbobbeaty** [comment]
The `Makefile` has an example test to run:

```bash
$ make test
```

and it runs the app with the following arguments:

```
./quip 'Fict O ncc bivteclnbklzn O lcpji ukl pt vzglcddp' -kb=t -fwords
```

and the options are pretty simple:

* `-k` is the key on a letter. In this case, `B` equals `T`.
* `-f` is the filename for the words, in this case `words` as it's in the root of the repo.

The argument that's in single quotes is the cyphertext. It's in quotes so that it can have spaces - important for separating words.

There are other args, all at the end of `quip.c`, but this is the easiest way to run it from the command line.

**Comment by ryankaka92** [comment]
I mostly worked with python and php was not able to figure out this on my own.
Huge thanks.

**Comment by drbobbeaty** [comment]
Solved. 👍
